name: sdek_plagin
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  yandex_maps_mapkit_lite:
    version: ^4.5.0
  shared_preferences: ^2.3.4
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  geolocator: ^13.0.2
  retrofit: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.0.0
  json_serializable: ^6.8.0

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true


